web:
  build: .
  links:
    - mysql
  ports:
    - "80:80"
  volumes:
    - ../:/var/www/html

mysql:
  image: mysql:5.6
  environment:
     - MYSQL_ROOT_PASSWORD=ventureoak
  volumes:
    - ./docker/data:/var/lib/mysql
  ports:
    - "3306:3306"
